import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
    en: {
        dropText: "Drop your videos here to lighten",
        browse: "Browse Files",
        files: "File Queue",
        queued: "Queued",
        processing: "Processing...",
        completed: "Done",
        settings: "Basic Settings",
        advanced: "Advanced Settings",
        format: "Output Format",
        resolution: "Resolution",
        audio: "Audio Control",
        removeAudio: "Remove Audio (Mute)",
        fileMgmt: "File Management",
        moveToTrash: "Move original to trash after compression",
        start: "Start Compression",
        stop: "Stop",
        totalProgress: "Total Progress",
        eta: "ETA",
        remove: "Remove",
        clearAll: "Clear All",
        theme: "Theme",
        language: "Language",
        subjectiveVQ: "Subjective VQ Tuning",
        subjectiveVQTip: "Applies an algorithm that finds the most natural quality for human eyes.",
        hdr: "10-bit HDR Support",
        hdrTip: "Supports high-bandwidth color for professional-grade video distribution.",
        deshake: "Video Stabilization (Deshake)",
        deshakeTip: "Reduces camera shake in handheld videos using FFmpeg's deshake filter.",
        metadata: "Metadata Cleaning",
        metadataTip: "Removes technical metadata (GPS, device info) to protect your privacy.",
        custom: "Custom",
        lockRatio: "Lock Ratio",
        quality: "Compression Quality",
        highQuality: "Quality",
        highCompression: "Compress",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Original Size",
        estResultText: "Est. Result",
        estReductionText: "Est. Batch Reduction",
        reductionOff: "OFF",
        batchNote: "Advanced SVT-AV1 scaling applied to {count} files",
        outputDest: "Saving Location",
        sameAsOriginal: "Same as original folder",
        selectFolder: "Select destination folder",
        saveTo: "Save to",
        legal: "Terms & Privacy",
        activateTitle: "Activate VideoLighter",
        activateSub: "Enter your license key to unlock powerful video compression.",
        licenseKey: "License Key",
        activateBtn: "Activate License",
        verifying: "Verifying your license...",
        buyNow: "Don't have a key? Buy one now",
        support: "Support",
        invalidKey: "Invalid or expired license key.",
        machineLocked: "This key is already registered to another device.",
        activationSuccess: "Activation successful! Welcome to VideoLighter.",
        turbo: "Turbo Acceleration Mode",
        turboTip: "Enables hardware acceleration and optimized SVT-AV1 presets for up to 3x faster compression.",
        parallel: "Parallel Compression",
        parallelTip: "Compresses multiple files at once. Speed depends on your CPU core count.",
        watermark: "Add Watermark",
        watermarkTip: "Overlays custom text on the bottom-right of the video for copyright protection.",
        thumbnail: "Generate Thumbnail",
        thumbnailTip: "Automatically extracts the best frame as a high-quality JPG image.",
        folderOpen: "Open in folder"
    },
    ko: {
        dropText: "동영상을 이곳에 드래그하여 용량을 줄이세요",
        browse: "파일 찾기",
        files: "파일 대기열",
        queued: "대기 중",
        processing: "처리 중...",
        completed: "완료",
        settings: "기본 설정",
        advanced: "고급 설정",
        format: "출력 형식",
        resolution: "해상도 조절",
        audio: "오디오 설정",
        removeAudio: "오디오 제거 (음소거)",
        fileMgmt: "파일 관리",
        moveToTrash: "압축 완료 후 원본 휴지통으로 이동",
        start: "압축 시작",
        stop: "중단",
        totalProgress: "전체 진행률",
        eta: "남은 시간",
        remove: "삭제",
        clearAll: "전체 삭제",
        theme: "테마",
        language: "언어",
        subjectiveVQ: "인지 화질 최적화",
        subjectiveVQTip: "사람이 보기에 가장 자연스러운 화질을 찾아주는 알고리즘을 적용합니다.",
        hdr: "10-bit HDR 지원",
        hdrTip: "전문가급 영상 배포를 위한 고대역폭 색상을 지원합니다.",
        deshake: "영상 안정화 (Deshake)",
        deshakeTip: "영상 필터를 사용하여 촬영 시 발생한 흔들림을 보정합니다.",
        metadata: "메타데이터 클리닝",
        metadataTip: "GPS, 기기 정보 등 사생활과 직결된 기술 정보를 깨끗이 제거합니다.",
        custom: "직접 입력",
        lockRatio: "비율 고정",
        quality: "압축률 설정",
        highQuality: "고화질",
        highCompression: "고압축",
        instagram: "인스타그램 (1080p)",
        youtube: "유튜브 (4K)",
        originalSizeText: "원본 용량",
        estResultText: "예상 결과",
        estReductionText: "평균 압축 효율",
        reductionOff: "감소",
        batchNote: "SVT-AV1 엔진이 {count}개의 파일을 최적화 중입니다",
        outputDest: "파일 저장 위치",
        sameAsOriginal: "원본 파일과 같은 폴더에 저장",
        selectFolder: "저장 위치 직접 선택",
        saveTo: "저장 경로",
        legal: "이용약관 및 개인정보 정책",
        activateTitle: "VideoLighter 활성화",
        activateSub: "라이선스 키를 입력하여 강력한 동영상 압축 기능을 잠금 해제하세요.",
        licenseKey: "라이선스 키 입력",
        activateBtn: "라이선스 활성화",
        verifying: "라이선스를 확인 중입니다...",
        buyNow: "라이선스 활성화 키가 없으신가요? 지금 구매하기",
        support: "고객 지원",
        invalidKey: "유효하지 않거나 만료된 키입니다.",
        machineLocked: "이 키는 이미 다른 기기에 등록되어 있습니다.",
        activationSuccess: "활성화 성공! VideoLighter의 모든 기능을 사용하실 수 있습니다.",
        turbo: "터보 가속 모드",
        turboTip: "하드웨어 가속(GPU) 및 최적화된 프리셋을 사용하여 압축 속도를 최대 3배 이상 높줍니다.",
        parallel: "다중 파일 동시 압축",
        parallelTip: "여러 파일을 동시에 압축합니다. CPU 코어 수가 많을수록 효과적입니다.",
        watermark: "워터마크 추가",
        watermarkTip: "영상 우측 하단에 사용자 지정 텍스트를 삽입하여 도용을 방지합니다.",
        thumbnail: "썸네일 자동 생성",
        thumbnailTip: "압축 완료 시 가장 선명한 장면을 JPG 이미지로 자동 추출합니다.",
        folderOpen: "저장 폴더 열기"
    }
};

export const FORMAT_OPTIONS = ['MP4', 'WebM', 'MKV', 'GIF'] as const;
export const RESOLUTION_OPTIONS = ['Original', '4K', '1080p', '720p', '480p', 'Instagram', 'YouTube', 'Custom'] as const;
