import { Translation, Language } from './types';

// iOS/Android와 동일한 10개국어 (ko/en/ja/zh/es/fr/de/pt/ru/hi).
// 브랜드명 "Velo", 기술용어(SVT-AV1, HDR, AV1, 1080p, 4K), 플랫폼명(Instagram, YouTube)은 원어 유지.

export const TRANSLATIONS: Record<Language, Translation> = {
    en: {
        dropText: "Drop your videos here to lighten",
        browse: "Browse Files",
        files: "File Queue",
        queued: "Queued",
        processing: "Processing...",
        completed: "Done",
        settings: "Basic Settings",
        advanced: "Advanced Settings",
        format: "Output Format",
        resolution: "Resolution",
        audio: "Audio Control",
        removeAudio: "Remove Audio (Mute)",
        fileMgmt: "File Management",
        moveToTrash: "Move original to trash after compression",
        start: "Start Compression",
        stop: "Stop",
        totalProgress: "Total Progress",
        eta: "ETA",
        remove: "Remove",
        clearAll: "Clear All",
        theme: "Theme",
        language: "Language",
        custom: "Custom",
        lockRatio: "Lock Ratio",
        quality: "Compression Quality",
        highQuality: "Quality",
        highCompression: "Compress",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Original Size",
        estResultText: "Est. Result",
        estReductionText: "Est. Batch Reduction",
        reductionOff: "OFF",
        batchNote: "Advanced SVT-AV1 scaling applied to {count} files",
        outputDest: "Saving Location",
        sameAsOriginal: "Same as original folder",
        selectFolder: "Select destination folder",
        saveTo: "Save to",
        legal: "Terms & Privacy",
        activateTitle: "Activate Velo",
        activateSub: "Enter your license key to unlock powerful video compression.",
        licenseKey: "License Key",
        activateBtn: "Activate License",
        verifying: "Verifying your license...",
        buyNow: "Don't have a key? Buy one now",
        support: "Support",
        invalidKey: "Invalid or expired license key.",
        machineLocked: "This key is already registered to another device.",
        activationSuccess: "Activation successful! Welcome to Velo.",
        turbo: "Turbo Acceleration Mode",
        turboTip: "Enables hardware acceleration and optimized SVT-AV1 presets for up to 3x faster compression.",
        parallel: "Parallel Processing",
        parallelTip: "Compress multiple videos at once. Higher numbers use more CPU.",

        bestQuality: "Best Quality",
        bestQualityDesc: "Visually identical to original. ~30-50% reduction.",
        balanced: "Balanced",
        balancedDesc: "Great for sharing. High quality, optimized size.",
        smallestSize: "Smallest Size",
        smallestSizeDesc: "Maximum compression for quick messaging.",

        subjectiveVQ: "Perceptual Quality Magic",
        subjectiveVQTip: "Focuses quality where human eyes notice most (faces, brightness). Reduces size while looking better!",
        hdr: "Keep HDR Colors (10-bit)",
        hdrTip: "Preserves the vivid colors of iPhone/Galaxy HDR videos. Essential for modern phone clips.",
        metadata: "Metadata Cleaning",
        metadataTip: "Removes technical metadata (GPS, device info) to protect your privacy.",

        highEfficiency: "Next-Gen Compression (AV1)",
        highEfficiencyTip: "Enables ~30% better compression using latest AV1 technology. Requires AV1 codec on playback device.",
        downloadCodec: "Download AV1 Codec",
        folderOpen: "Open in folder",
        taskType: "Task Type",
        videoMode: "Video Compression",
        imageMode: "Image Compression",
        individualMode: "Individual",
        folderMode: "Folder",
        imageSettings: "Image Compression Settings",
        signIn: "Sign in",
        signOut: "Sign out",
        receivedFiles: "Synced files",
        myDevices: "My devices",
        updateAvailable: "A new version is available. Update is recommended.",
        updateButton: "Update",
        dismissButton: "Dismiss",
        folderDropPrompt: "Drag a folder here or click to pick one",
        folderDropDescription: "Recursive scan of all subfolders · batch compress media",
        folderDropOutput: "Output: {root}/_velo_compressed/ (auto)",
        folderFilesUnit: "files",
        folderPickAnother: "Pick another",
        folderScannedFiles: "Scanned files",
        folderEmpty: "No compressible files found.",
        folderExcludeTooltip: "Exclude",
        readyToProcess: "Ready to process {count} files",
    },
    ko: {
        dropText: "동영상을 이곳에 드래그하여 용량을 줄이세요",
        browse: "파일 찾기",
        files: "파일 대기열",
        queued: "대기 중",
        processing: "처리 중...",
        completed: "완료",
        settings: "기본 설정",
        advanced: "고급 설정",
        format: "출력 형식",
        resolution: "해상도 조절",
        audio: "오디오 설정",
        removeAudio: "오디오 제거 (음소거)",
        fileMgmt: "파일 관리",
        moveToTrash: "압축 완료 후 원본 휴지통으로 이동",
        start: "압축 시작",
        stop: "중단",
        totalProgress: "전체 진행률",
        eta: "남은 시간",
        remove: "삭제",
        clearAll: "전체 삭제",
        theme: "테마",
        language: "언어",
        custom: "직접 입력",
        lockRatio: "비율 고정",
        quality: "압축률 설정",
        highQuality: "고화질",
        highCompression: "고압축",
        instagram: "인스타그램 (1080p)",
        youtube: "유튜브 (4K)",
        originalSizeText: "원본 용량",
        estResultText: "예상 결과",
        estReductionText: "평균 압축 효율",
        reductionOff: "감소",
        batchNote: "SVT-AV1 엔진이 {count}개의 파일을 최적화 중입니다",
        outputDest: "파일 저장 위치",
        sameAsOriginal: "원본 파일과 같은 폴더에 저장",
        selectFolder: "저장 위치 직접 선택",
        saveTo: "저장 경로",
        legal: "이용약관 및 개인정보 정책",
        activateTitle: "Velo 활성화",
        activateSub: "라이선스 키를 입력하여 강력한 동영상 압축 기능을 잠금 해제하세요.",
        licenseKey: "라이선스 키 입력",
        activateBtn: "라이선스 활성화",
        verifying: "라이선스를 확인 중입니다...",
        buyNow: "라이선스 활성화 키가 없으신가요? 지금 구매하기",
        support: "고객 지원",
        invalidKey: "유효하지 않거나 만료된 키입니다.",
        machineLocked: "이 키는 이미 다른 기기에 등록되어 있습니다.",
        activationSuccess: "활성화 성공! Velo의 모든 기능을 사용하실 수 있습니다.",
        turbo: "터보 가속 모드",
        turboTip: "하드웨어 가속(GPU) 및 최적화된 프리셋을 사용하여 압축 속도를 최대 3배 이상 높줍니다.",
        parallel: "병렬 압축",
        parallelTip: "여러 파일을 동시에 압축합니다. CPU 성능에 따라 속도가 달라집니다.",

        bestQuality: "최고 화질",
        bestQualityDesc: "원본과 거의 동일한 화질. 용량은 30-50% 줄어듭니다.",
        balanced: "균형 모드 (추천)",
        balancedDesc: "공유하기 딱 좋은 품질과 용량입니다. 가장 안전한 선택!",
        smallestSize: "용량 우선",
        smallestSizeDesc: "카톡 전송용으로 최고! 용량을 극한까지 줄입니다.",

        subjectiveVQ: "인지 화질 최적화 (매직)",
        subjectiveVQTip: "기계적인 계산 대신, 사람 눈이 민감한 곳(얼굴 등) 위주로 화질을 챙깁니다. 용량은 더 줄고 화질은 더 좋아 보입니다!",
        hdr: "HDR 색감 유지 (10-bit)",
        hdrTip: "전문가급 영상 배포를 위한 고대역폭 색상을 지원합니다.",
        metadata: "메타데이터 클리닝",
        metadataTip: "GPS, 기기 정보 등 사생활과 직결된 기술 정보를 깨끗이 제거합니다.",

        folderOpen: "저장 폴더 열기",
        highEfficiency: "차세대 고압축 (AV1)",
        highEfficiencyTip: "최신 AV1 기술로 30% 더 압축합니다. 재생 기기에 AV1 코덱이 필요할 수 있습니다.",
        downloadCodec: "AV1 코덱 다운로드 (무료)",
        taskType: "작업 타입",
        videoMode: "동영상 압축",
        imageMode: "이미지 압축",
        individualMode: "개별 압축",
        folderMode: "폴더 압축",
        imageSettings: "이미지 압축 설정",
        signIn: "로그인",
        signOut: "로그아웃",
        receivedFiles: "동기화된 파일",
        myDevices: "내 기기",
        updateAvailable: "새 버전이 있습니다. 업데이트를 권장합니다.",
        updateButton: "업데이트",
        dismissButton: "닫기",
        folderDropPrompt: "폴더를 드래그하거나 클릭하여 선택하세요",
        folderDropDescription: "하위 모든 폴더까지 재귀 스캔 · 영상/이미지 일괄 압축",
        folderDropOutput: "출력: {root}/_velo_compressed/ (자동 생성)",
        folderFilesUnit: "개",
        folderPickAnother: "다른 폴더",
        folderScannedFiles: "스캔된 파일",
        folderEmpty: "압축 가능한 파일이 없습니다.",
        folderExcludeTooltip: "제외",
        readyToProcess: "{count}개 파일 처리 대기",
    },
    ja: {
        dropText: "動画をここにドラッグして容量を減らす",
        browse: "ファイルを選択",
        files: "ファイルキュー",
        queued: "待機中",
        processing: "処理中...",
        completed: "完了",
        settings: "基本設定",
        advanced: "詳細設定",
        format: "出力形式",
        resolution: "解像度",
        audio: "オーディオ設定",
        removeAudio: "音声を削除(ミュート)",
        fileMgmt: "ファイル管理",
        moveToTrash: "圧縮完了後、元ファイルをゴミ箱へ",
        start: "圧縮開始",
        stop: "停止",
        totalProgress: "全体の進捗",
        eta: "残り時間",
        remove: "削除",
        clearAll: "すべてクリア",
        theme: "テーマ",
        language: "言語",
        custom: "カスタム",
        lockRatio: "比率を固定",
        quality: "圧縮品質",
        highQuality: "高画質",
        highCompression: "高圧縮",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "元のサイズ",
        estResultText: "予想結果",
        estReductionText: "平均圧縮率",
        reductionOff: "削減",
        batchNote: "SVT-AV1エンジンが{count}個のファイルを最適化中",
        outputDest: "保存場所",
        sameAsOriginal: "元ファイルと同じフォルダに保存",
        selectFolder: "保存先フォルダを選択",
        saveTo: "保存先",
        legal: "利用規約・プライバシー",
        activateTitle: "Veloを有効化",
        activateSub: "ライセンスキーを入力して強力な動画圧縮機能を有効化してください。",
        licenseKey: "ライセンスキー",
        activateBtn: "ライセンスを有効化",
        verifying: "ライセンスを確認中...",
        buyNow: "キーをお持ちでない方はこちらから購入",
        support: "サポート",
        invalidKey: "無効または期限切れのキーです。",
        machineLocked: "このキーは別の端末に登録されています。",
        activationSuccess: "有効化に成功しました!Veloのすべての機能をご利用いただけます。",
        turbo: "ターボ加速モード",
        turboTip: "ハードウェア加速と最適化されたSVT-AV1プリセットで最大3倍速い圧縮を実現します。",
        parallel: "並列圧縮",
        parallelTip: "複数の動画を同時に圧縮します。数値が大きいほどCPU使用率が上がります。",

        bestQuality: "最高画質",
        bestQualityDesc: "元動画とほぼ同じ画質。容量は30-50%削減。",
        balanced: "バランス(推奨)",
        balancedDesc: "共有に最適な画質と容量。一番安心の選択。",
        smallestSize: "容量優先",
        smallestSizeDesc: "メッセージ送信に最適。容量を極限まで削減。",

        subjectiveVQ: "知覚画質最適化(マジック)",
        subjectiveVQTip: "機械的な計算ではなく、人間の目が敏感な部分(顔など)を中心に画質を維持します。容量は減り、見た目はより美しく!",
        hdr: "HDR色彩を維持(10-bit)",
        hdrTip: "iPhone/Galaxy HDR動画の鮮やかな色を保ちます。最新のスマホ動画には必須。",
        metadata: "メタデータ削除",
        metadataTip: "GPSや端末情報など、プライバシーに関わる情報をきれいに削除します。",

        highEfficiency: "次世代圧縮(AV1)",
        highEfficiencyTip: "最新のAV1技術で約30%多く圧縮。再生機器にAV1コーデックが必要です。",
        downloadCodec: "AV1コーデックをダウンロード",
        folderOpen: "フォルダを開く",
        taskType: "作業タイプ",
        videoMode: "動画圧縮",
        imageMode: "画像圧縮",
        individualMode: "個別",
        folderMode: "フォルダ",
        imageSettings: "画像圧縮設定",
        signIn: "ログイン",
        signOut: "ログアウト",
        receivedFiles: "同期されたファイル",
        myDevices: "マイデバイス",
        updateAvailable: "新しいバージョンがあります。アップデートをおすすめします。",
        updateButton: "アップデート",
        dismissButton: "閉じる",
        folderDropPrompt: "フォルダをドラッグまたはクリックして選択",
        folderDropDescription: "サブフォルダまで再帰スキャン · 動画/画像を一括圧縮",
        folderDropOutput: "出力: {root}/_velo_compressed/ (自動生成)",
        folderFilesUnit: "個",
        folderPickAnother: "別のフォルダ",
        folderScannedFiles: "スキャン済みファイル",
        folderEmpty: "圧縮可能なファイルがありません。",
        folderExcludeTooltip: "除外",
        readyToProcess: "{count}個のファイルを処理待機中",
    },
    zh: {
        dropText: "拖动视频到此处以减小容量",
        browse: "选择文件",
        files: "文件队列",
        queued: "等待中",
        processing: "处理中...",
        completed: "已完成",
        settings: "基本设置",
        advanced: "高级设置",
        format: "输出格式",
        resolution: "分辨率",
        audio: "音频设置",
        removeAudio: "移除音频(静音)",
        fileMgmt: "文件管理",
        moveToTrash: "压缩完成后将原件移至回收站",
        start: "开始压缩",
        stop: "停止",
        totalProgress: "总进度",
        eta: "剩余时间",
        remove: "删除",
        clearAll: "全部清除",
        theme: "主题",
        language: "语言",
        custom: "自定义",
        lockRatio: "锁定比例",
        quality: "压缩质量",
        highQuality: "高质量",
        highCompression: "高压缩",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "原始大小",
        estResultText: "预计结果",
        estReductionText: "平均压缩率",
        reductionOff: "减少",
        batchNote: "SVT-AV1引擎正在优化{count}个文件",
        outputDest: "保存位置",
        sameAsOriginal: "保存到原文件相同文件夹",
        selectFolder: "选择保存文件夹",
        saveTo: "保存到",
        legal: "条款与隐私",
        activateTitle: "激活Velo",
        activateSub: "输入许可证密钥以解锁强大的视频压缩功能。",
        licenseKey: "许可证密钥",
        activateBtn: "激活许可证",
        verifying: "正在验证许可证...",
        buyNow: "没有密钥?立即购买",
        support: "客户支持",
        invalidKey: "无效或已过期的密钥。",
        machineLocked: "此密钥已注册到其他设备。",
        activationSuccess: "激活成功!欢迎使用Velo。",
        turbo: "加速模式",
        turboTip: "启用硬件加速和优化的SVT-AV1预设,压缩速度提升至多3倍。",
        parallel: "并行压缩",
        parallelTip: "同时压缩多个视频。数值越大,占用CPU越多。",

        bestQuality: "最佳质量",
        bestQualityDesc: "与原视频画质几乎相同。容量减少30-50%。",
        balanced: "平衡模式(推荐)",
        balancedDesc: "适合分享的高质量与容量平衡。最稳妥选择。",
        smallestSize: "容量优先",
        smallestSizeDesc: "适合即时通讯。容量压到极致。",

        subjectiveVQ: "感知质量优化(魔法)",
        subjectiveVQTip: "不依赖机械计算,围绕人眼敏感的区域(如人脸)保留质量。容量更小,观感更好!",
        hdr: "保留HDR色彩(10-bit)",
        hdrTip: "保留iPhone/Galaxy HDR视频鲜艳的色彩。现代手机视频必备。",
        metadata: "元数据清理",
        metadataTip: "移除GPS、设备信息等技术元数据,保护隐私。",

        highEfficiency: "新一代压缩(AV1)",
        highEfficiencyTip: "使用最新AV1技术多压缩约30%。播放设备需支持AV1解码。",
        downloadCodec: "下载AV1解码器",
        folderOpen: "打开文件夹",
        taskType: "任务类型",
        videoMode: "视频压缩",
        imageMode: "图片压缩",
        individualMode: "单个",
        folderMode: "文件夹",
        imageSettings: "图片压缩设置",
        signIn: "登录",
        signOut: "登出",
        receivedFiles: "已同步文件",
        myDevices: "我的设备",
        updateAvailable: "有新版本可用。建议更新。",
        updateButton: "更新",
        dismissButton: "关闭",
        folderDropPrompt: "拖动文件夹到此处或点击选择",
        folderDropDescription: "递归扫描所有子文件夹 · 批量压缩媒体",
        folderDropOutput: "输出: {root}/_velo_compressed/ (自动生成)",
        folderFilesUnit: "个",
        folderPickAnother: "选择其他",
        folderScannedFiles: "已扫描文件",
        folderEmpty: "没有可压缩的文件。",
        folderExcludeTooltip: "排除",
        readyToProcess: "{count} 个文件待处理",
    },
    es: {
        dropText: "Arrastra tus videos aquí para reducir su tamaño",
        browse: "Buscar archivos",
        files: "Cola de archivos",
        queued: "En cola",
        processing: "Procesando...",
        completed: "Listo",
        settings: "Ajustes básicos",
        advanced: "Ajustes avanzados",
        format: "Formato de salida",
        resolution: "Resolución",
        audio: "Audio",
        removeAudio: "Quitar audio (silenciar)",
        fileMgmt: "Gestión de archivos",
        moveToTrash: "Mover original a la papelera tras la compresión",
        start: "Iniciar compresión",
        stop: "Detener",
        totalProgress: "Progreso total",
        eta: "Tiempo restante",
        remove: "Eliminar",
        clearAll: "Limpiar todo",
        theme: "Tema",
        language: "Idioma",
        custom: "Personalizado",
        lockRatio: "Bloquear proporción",
        quality: "Calidad de compresión",
        highQuality: "Calidad",
        highCompression: "Comprimir",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Tamaño original",
        estResultText: "Resultado estimado",
        estReductionText: "Reducción media",
        reductionOff: "OFF",
        batchNote: "El motor SVT-AV1 está optimizando {count} archivos",
        outputDest: "Ubicación de guardado",
        sameAsOriginal: "Misma carpeta que el original",
        selectFolder: "Seleccionar carpeta de destino",
        saveTo: "Guardar en",
        legal: "Términos y privacidad",
        activateTitle: "Activar Velo",
        activateSub: "Introduce tu clave de licencia para desbloquear la compresión potente de vídeo.",
        licenseKey: "Clave de licencia",
        activateBtn: "Activar licencia",
        verifying: "Verificando licencia...",
        buyNow: "¿No tienes clave? Cómprala ahora",
        support: "Soporte",
        invalidKey: "Clave inválida o caducada.",
        machineLocked: "Esta clave ya está registrada en otro dispositivo.",
        activationSuccess: "¡Activación correcta! Bienvenido a Velo.",
        turbo: "Modo Turbo",
        turboTip: "Acelera la compresión hasta 3 veces con aceleración por hardware y presets SVT-AV1 optimizados.",
        parallel: "Procesamiento paralelo",
        parallelTip: "Comprime varios vídeos a la vez. Cuanto mayor sea el número, más CPU se usa.",

        bestQuality: "Máxima calidad",
        bestQualityDesc: "Visualmente idéntico al original. Reducción de 30-50%.",
        balanced: "Equilibrado",
        balancedDesc: "Ideal para compartir. Buena calidad y tamaño optimizado.",
        smallestSize: "Mínimo tamaño",
        smallestSizeDesc: "Compresión máxima para mensajería rápida.",

        subjectiveVQ: "Magia de calidad perceptual",
        subjectiveVQTip: "Centra la calidad donde el ojo humano lo nota más (caras, brillo). Menor tamaño y mejor aspecto.",
        hdr: "Mantener colores HDR (10 bits)",
        hdrTip: "Conserva los colores vivos de los vídeos HDR de iPhone/Galaxy. Esencial para móviles modernos.",
        metadata: "Limpieza de metadatos",
        metadataTip: "Elimina metadatos técnicos (GPS, info del dispositivo) para proteger tu privacidad.",

        highEfficiency: "Compresión de nueva generación (AV1)",
        highEfficiencyTip: "Comprime un 30% más con la tecnología AV1. El dispositivo de reproducción debe soportar AV1.",
        downloadCodec: "Descargar códec AV1",
        folderOpen: "Abrir en carpeta",
        taskType: "Tipo de tarea",
        videoMode: "Compresión de vídeo",
        imageMode: "Compresión de imagen",
        individualMode: "Individual",
        folderMode: "Carpeta",
        imageSettings: "Ajustes de compresión de imagen",
        signIn: "Iniciar sesión",
        signOut: "Cerrar sesión",
        receivedFiles: "Archivos sincronizados",
        myDevices: "Mis dispositivos",
        updateAvailable: "Hay una nueva versión disponible. Se recomienda actualizar.",
        updateButton: "Actualizar",
        dismissButton: "Cerrar",
        folderDropPrompt: "Arrastra una carpeta aquí o haz clic para elegir",
        folderDropDescription: "Escaneo recursivo de subcarpetas · compresión por lotes",
        folderDropOutput: "Salida: {root}/_velo_compressed/ (automático)",
        folderFilesUnit: "archivos",
        folderPickAnother: "Elegir otra",
        folderScannedFiles: "Archivos escaneados",
        folderEmpty: "No se encontraron archivos comprimibles.",
        folderExcludeTooltip: "Excluir",
        readyToProcess: "Listo para procesar {count} archivos",
    },
    fr: {
        dropText: "Glissez vos vidéos ici pour réduire leur taille",
        browse: "Parcourir les fichiers",
        files: "File d'attente",
        queued: "En attente",
        processing: "Traitement en cours...",
        completed: "Terminé",
        settings: "Paramètres de base",
        advanced: "Paramètres avancés",
        format: "Format de sortie",
        resolution: "Résolution",
        audio: "Audio",
        removeAudio: "Supprimer l'audio (muet)",
        fileMgmt: "Gestion des fichiers",
        moveToTrash: "Déplacer l'original à la corbeille après compression",
        start: "Démarrer la compression",
        stop: "Arrêter",
        totalProgress: "Progression totale",
        eta: "Temps restant",
        remove: "Supprimer",
        clearAll: "Tout effacer",
        theme: "Thème",
        language: "Langue",
        custom: "Personnalisé",
        lockRatio: "Verrouiller le ratio",
        quality: "Qualité de compression",
        highQuality: "Qualité",
        highCompression: "Compression",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Taille originale",
        estResultText: "Résultat estimé",
        estReductionText: "Réduction moyenne",
        reductionOff: "OFF",
        batchNote: "Le moteur SVT-AV1 optimise {count} fichiers",
        outputDest: "Emplacement de sauvegarde",
        sameAsOriginal: "Même dossier que l'original",
        selectFolder: "Sélectionner le dossier de destination",
        saveTo: "Enregistrer dans",
        legal: "Conditions et confidentialité",
        activateTitle: "Activer Velo",
        activateSub: "Entrez votre clé de licence pour débloquer la compression vidéo puissante.",
        licenseKey: "Clé de licence",
        activateBtn: "Activer la licence",
        verifying: "Vérification de la licence...",
        buyNow: "Pas de clé ? Achetez-en une maintenant",
        support: "Support",
        invalidKey: "Clé invalide ou expirée.",
        machineLocked: "Cette clé est déjà enregistrée sur un autre appareil.",
        activationSuccess: "Activation réussie ! Bienvenue dans Velo.",
        turbo: "Mode Turbo",
        turboTip: "Active l'accélération matérielle et les préréglages SVT-AV1 pour une compression jusqu'à 3 fois plus rapide.",
        parallel: "Traitement parallèle",
        parallelTip: "Compresser plusieurs vidéos à la fois. Plus la valeur est élevée, plus le CPU est sollicité.",

        bestQuality: "Meilleure qualité",
        bestQualityDesc: "Visuellement identique à l'original. Réduction d'environ 30-50%.",
        balanced: "Équilibré",
        balancedDesc: "Idéal pour le partage. Bonne qualité, taille optimisée.",
        smallestSize: "Taille minimale",
        smallestSizeDesc: "Compression maximale pour messagerie rapide.",

        subjectiveVQ: "Magie de qualité perceptive",
        subjectiveVQTip: "Concentre la qualité où l'œil humain est le plus sensible (visages, luminosité). Réduit la taille tout en améliorant l'apparence.",
        hdr: "Conserver les couleurs HDR (10 bits)",
        hdrTip: "Préserve les couleurs vives des vidéos HDR iPhone/Galaxy. Essentiel pour les vidéos de smartphone modernes.",
        metadata: "Nettoyage des métadonnées",
        metadataTip: "Supprime les métadonnées techniques (GPS, info appareil) pour protéger votre vie privée.",

        highEfficiency: "Compression nouvelle génération (AV1)",
        highEfficiencyTip: "Compresse environ 30% de plus avec la technologie AV1. Nécessite un codec AV1 sur l'appareil de lecture.",
        downloadCodec: "Télécharger le codec AV1",
        folderOpen: "Ouvrir le dossier",
        taskType: "Type de tâche",
        videoMode: "Compression vidéo",
        imageMode: "Compression d'image",
        individualMode: "Individuel",
        folderMode: "Dossier",
        imageSettings: "Paramètres de compression d'image",
        signIn: "Connexion",
        signOut: "Déconnexion",
        receivedFiles: "Fichiers synchronisés",
        myDevices: "Mes appareils",
        updateAvailable: "Une nouvelle version est disponible. Mise à jour recommandée.",
        updateButton: "Mettre à jour",
        dismissButton: "Fermer",
        folderDropPrompt: "Glissez un dossier ici ou cliquez pour en choisir un",
        folderDropDescription: "Scan récursif de tous les sous-dossiers · compression par lots",
        folderDropOutput: "Sortie : {root}/_velo_compressed/ (auto)",
        folderFilesUnit: "fichiers",
        folderPickAnother: "Autre dossier",
        folderScannedFiles: "Fichiers scannés",
        folderEmpty: "Aucun fichier compressible trouvé.",
        folderExcludeTooltip: "Exclure",
        readyToProcess: "Prêt à traiter {count} fichiers",
    },
    de: {
        dropText: "Videos hier ablegen, um die Größe zu reduzieren",
        browse: "Dateien auswählen",
        files: "Datei-Warteschlange",
        queued: "Wartend",
        processing: "Wird verarbeitet...",
        completed: "Fertig",
        settings: "Grundeinstellungen",
        advanced: "Erweiterte Einstellungen",
        format: "Ausgabeformat",
        resolution: "Auflösung",
        audio: "Audio",
        removeAudio: "Audio entfernen (stumm)",
        fileMgmt: "Dateiverwaltung",
        moveToTrash: "Original nach Komprimierung in den Papierkorb verschieben",
        start: "Komprimierung starten",
        stop: "Stoppen",
        totalProgress: "Gesamtfortschritt",
        eta: "Verbleibende Zeit",
        remove: "Entfernen",
        clearAll: "Alle löschen",
        theme: "Design",
        language: "Sprache",
        custom: "Benutzerdefiniert",
        lockRatio: "Seitenverhältnis sperren",
        quality: "Komprimierungsqualität",
        highQuality: "Qualität",
        highCompression: "Komprimieren",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Originalgröße",
        estResultText: "Geschätztes Ergebnis",
        estReductionText: "Durchschn. Reduktion",
        reductionOff: "OFF",
        batchNote: "SVT-AV1-Engine optimiert {count} Dateien",
        outputDest: "Speicherort",
        sameAsOriginal: "Gleicher Ordner wie das Original",
        selectFolder: "Zielordner auswählen",
        saveTo: "Speichern unter",
        legal: "AGB & Datenschutz",
        activateTitle: "Velo aktivieren",
        activateSub: "Lizenzschlüssel eingeben, um die leistungsstarke Videokomprimierung freizuschalten.",
        licenseKey: "Lizenzschlüssel",
        activateBtn: "Lizenz aktivieren",
        verifying: "Lizenz wird überprüft...",
        buyNow: "Keinen Schlüssel? Jetzt kaufen",
        support: "Support",
        invalidKey: "Ungültiger oder abgelaufener Schlüssel.",
        machineLocked: "Dieser Schlüssel ist bereits auf einem anderen Gerät registriert.",
        activationSuccess: "Aktivierung erfolgreich! Willkommen bei Velo.",
        turbo: "Turbo-Modus",
        turboTip: "Aktiviert Hardwarebeschleunigung und optimierte SVT-AV1-Presets für bis zu 3-fach schnellere Komprimierung.",
        parallel: "Parallele Verarbeitung",
        parallelTip: "Mehrere Videos gleichzeitig komprimieren. Höhere Werte beanspruchen mehr CPU.",

        bestQuality: "Beste Qualität",
        bestQualityDesc: "Optisch identisch zum Original. ~30-50% Reduzierung.",
        balanced: "Ausgewogen",
        balancedDesc: "Ideal zum Teilen. Hohe Qualität, optimierte Größe.",
        smallestSize: "Kleinste Größe",
        smallestSizeDesc: "Maximale Komprimierung für schnelle Nachrichten.",

        subjectiveVQ: "Wahrnehmungs-Qualitätsmagie",
        subjectiveVQTip: "Fokussiert die Qualität dort, wo das menschliche Auge sie am ehesten wahrnimmt (Gesichter, Helligkeit). Kleinere Größe, bessere Optik.",
        hdr: "HDR-Farben beibehalten (10-bit)",
        hdrTip: "Erhält die lebendigen Farben von iPhone-/Galaxy-HDR-Videos. Wichtig für moderne Handyclips.",
        metadata: "Metadaten-Bereinigung",
        metadataTip: "Entfernt technische Metadaten (GPS, Geräteinfo) zum Schutz Ihrer Privatsphäre.",

        highEfficiency: "Komprimierung der nächsten Generation (AV1)",
        highEfficiencyTip: "Etwa 30% bessere Komprimierung mit AV1-Technologie. Benötigt AV1-Codec auf dem Wiedergabegerät.",
        downloadCodec: "AV1-Codec herunterladen",
        folderOpen: "Im Ordner öffnen",
        taskType: "Aufgabentyp",
        videoMode: "Videokomprimierung",
        imageMode: "Bildkomprimierung",
        individualMode: "Einzeln",
        folderMode: "Ordner",
        imageSettings: "Bildkomprimierungs-Einstellungen",
        signIn: "Anmelden",
        signOut: "Abmelden",
        receivedFiles: "Synchronisierte Dateien",
        myDevices: "Meine Geräte",
        updateAvailable: "Eine neue Version ist verfügbar. Update empfohlen.",
        updateButton: "Aktualisieren",
        dismissButton: "Schließen",
        folderDropPrompt: "Ordner hier ablegen oder zum Auswählen klicken",
        folderDropDescription: "Rekursiver Scan aller Unterordner · Batch-Komprimierung",
        folderDropOutput: "Ausgabe: {root}/_velo_compressed/ (automatisch)",
        folderFilesUnit: "Dateien",
        folderPickAnother: "Anderer Ordner",
        folderScannedFiles: "Gescannte Dateien",
        folderEmpty: "Keine komprimierbaren Dateien gefunden.",
        folderExcludeTooltip: "Ausschließen",
        readyToProcess: "Bereit zur Verarbeitung von {count} Dateien",
    },
    pt: {
        dropText: "Arraste seus vídeos aqui para reduzir o tamanho",
        browse: "Procurar arquivos",
        files: "Fila de arquivos",
        queued: "Em espera",
        processing: "Processando...",
        completed: "Concluído",
        settings: "Configurações básicas",
        advanced: "Configurações avançadas",
        format: "Formato de saída",
        resolution: "Resolução",
        audio: "Áudio",
        removeAudio: "Remover áudio (mudo)",
        fileMgmt: "Gestão de arquivos",
        moveToTrash: "Mover original para a lixeira após a compressão",
        start: "Iniciar compressão",
        stop: "Parar",
        totalProgress: "Progresso total",
        eta: "Tempo restante",
        remove: "Remover",
        clearAll: "Limpar tudo",
        theme: "Tema",
        language: "Idioma",
        custom: "Personalizado",
        lockRatio: "Travar proporção",
        quality: "Qualidade da compressão",
        highQuality: "Qualidade",
        highCompression: "Comprimir",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Tamanho original",
        estResultText: "Resultado estimado",
        estReductionText: "Redução média",
        reductionOff: "OFF",
        batchNote: "O motor SVT-AV1 está otimizando {count} arquivos",
        outputDest: "Local de salvamento",
        sameAsOriginal: "Mesma pasta do original",
        selectFolder: "Selecionar pasta de destino",
        saveTo: "Salvar em",
        legal: "Termos e privacidade",
        activateTitle: "Ativar Velo",
        activateSub: "Insira sua chave de licença para desbloquear a poderosa compressão de vídeo.",
        licenseKey: "Chave de licença",
        activateBtn: "Ativar licença",
        verifying: "Verificando licença...",
        buyNow: "Não tem uma chave? Compre agora",
        support: "Suporte",
        invalidKey: "Chave inválida ou expirada.",
        machineLocked: "Esta chave já está registrada em outro dispositivo.",
        activationSuccess: "Ativação bem-sucedida! Bem-vindo ao Velo.",
        turbo: "Modo Turbo",
        turboTip: "Ativa aceleração de hardware e presets SVT-AV1 otimizados para compressão até 3 vezes mais rápida.",
        parallel: "Processamento paralelo",
        parallelTip: "Comprima vários vídeos de uma só vez. Valores mais altos usam mais CPU.",

        bestQuality: "Melhor qualidade",
        bestQualityDesc: "Visualmente idêntico ao original. Redução de ~30-50%.",
        balanced: "Equilibrado",
        balancedDesc: "Ótimo para compartilhar. Boa qualidade, tamanho otimizado.",
        smallestSize: "Menor tamanho",
        smallestSizeDesc: "Compressão máxima para mensagens rápidas.",

        subjectiveVQ: "Magia de qualidade perceptual",
        subjectiveVQTip: "Foca a qualidade onde o olho humano percebe mais (rostos, brilho). Reduz tamanho mantendo boa aparência.",
        hdr: "Manter cores HDR (10-bit)",
        hdrTip: "Preserva as cores vívidas dos vídeos HDR de iPhone/Galaxy. Essencial para celulares modernos.",
        metadata: "Limpeza de metadados",
        metadataTip: "Remove metadados técnicos (GPS, info do dispositivo) para proteger sua privacidade.",

        highEfficiency: "Compressão de nova geração (AV1)",
        highEfficiencyTip: "Comprime ~30% melhor com tecnologia AV1. Requer codec AV1 no dispositivo de reprodução.",
        downloadCodec: "Baixar codec AV1",
        folderOpen: "Abrir na pasta",
        taskType: "Tipo de tarefa",
        videoMode: "Compressão de vídeo",
        imageMode: "Compressão de imagem",
        individualMode: "Individual",
        folderMode: "Pasta",
        imageSettings: "Configurações de compressão de imagem",
        signIn: "Entrar",
        signOut: "Sair",
        receivedFiles: "Arquivos sincronizados",
        myDevices: "Meus dispositivos",
        updateAvailable: "Uma nova versão está disponível. Atualização recomendada.",
        updateButton: "Atualizar",
        dismissButton: "Fechar",
        folderDropPrompt: "Arraste uma pasta aqui ou clique para escolher",
        folderDropDescription: "Varredura recursiva de subpastas · compressão em lote",
        folderDropOutput: "Saída: {root}/_velo_compressed/ (automático)",
        folderFilesUnit: "arquivos",
        folderPickAnother: "Outra pasta",
        folderScannedFiles: "Arquivos varridos",
        folderEmpty: "Nenhum arquivo compressível encontrado.",
        folderExcludeTooltip: "Excluir",
        readyToProcess: "Pronto para processar {count} arquivos",
    },
    ru: {
        dropText: "Перетащите видео сюда, чтобы уменьшить размер",
        browse: "Выбрать файлы",
        files: "Очередь файлов",
        queued: "В очереди",
        processing: "Обработка...",
        completed: "Готово",
        settings: "Основные настройки",
        advanced: "Расширенные настройки",
        format: "Формат вывода",
        resolution: "Разрешение",
        audio: "Звук",
        removeAudio: "Удалить звук (без звука)",
        fileMgmt: "Управление файлами",
        moveToTrash: "Перенести оригинал в корзину после сжатия",
        start: "Начать сжатие",
        stop: "Остановить",
        totalProgress: "Общий прогресс",
        eta: "Осталось",
        remove: "Удалить",
        clearAll: "Очистить всё",
        theme: "Тема",
        language: "Язык",
        custom: "Пользовательский",
        lockRatio: "Зафиксировать пропорции",
        quality: "Качество сжатия",
        highQuality: "Качество",
        highCompression: "Сжатие",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "Исходный размер",
        estResultText: "Оценка результата",
        estReductionText: "Средняя экономия",
        reductionOff: "OFF",
        batchNote: "Движок SVT-AV1 оптимизирует {count} файлов",
        outputDest: "Папка сохранения",
        sameAsOriginal: "Та же папка, что и оригинал",
        selectFolder: "Выбрать папку назначения",
        saveTo: "Сохранить в",
        legal: "Условия и конфиденциальность",
        activateTitle: "Активировать Velo",
        activateSub: "Введите лицензионный ключ, чтобы разблокировать мощное сжатие видео.",
        licenseKey: "Лицензионный ключ",
        activateBtn: "Активировать лицензию",
        verifying: "Проверка лицензии...",
        buyNow: "Нет ключа? Купить сейчас",
        support: "Поддержка",
        invalidKey: "Недействительный или просроченный ключ.",
        machineLocked: "Этот ключ уже зарегистрирован на другом устройстве.",
        activationSuccess: "Активация успешна! Добро пожаловать в Velo.",
        turbo: "Турбо-режим",
        turboTip: "Включает аппаратное ускорение и оптимизированные пресеты SVT-AV1 для ускорения сжатия до 3 раз.",
        parallel: "Параллельная обработка",
        parallelTip: "Сжимайте несколько видео одновременно. Большие значения используют больше CPU.",

        bestQuality: "Наилучшее качество",
        bestQualityDesc: "Визуально идентично оригиналу. Сокращение ~30-50%.",
        balanced: "Сбалансированный",
        balancedDesc: "Отлично для отправки. Хорошее качество, оптимизированный размер.",
        smallestSize: "Минимальный размер",
        smallestSizeDesc: "Максимальное сжатие для быстрых сообщений.",

        subjectiveVQ: "Магия перцептивного качества",
        subjectiveVQTip: "Фокусирует качество там, где это заметно глазу (лица, яркость). Меньший размер, лучший вид.",
        hdr: "Сохранить цвета HDR (10-бит)",
        hdrTip: "Сохраняет яркие цвета HDR-видео iPhone/Galaxy. Важно для современных смартфонов.",
        metadata: "Очистка метаданных",
        metadataTip: "Удаляет технические метаданные (GPS, информация об устройстве) для защиты конфиденциальности.",

        highEfficiency: "Сжатие нового поколения (AV1)",
        highEfficiencyTip: "Сжимает на ~30% лучше с технологией AV1. На устройстве воспроизведения нужен кодек AV1.",
        downloadCodec: "Скачать кодек AV1",
        folderOpen: "Открыть в папке",
        taskType: "Тип задачи",
        videoMode: "Сжатие видео",
        imageMode: "Сжатие изображений",
        individualMode: "Отдельные",
        folderMode: "Папка",
        imageSettings: "Настройки сжатия изображений",
        signIn: "Войти",
        signOut: "Выйти",
        receivedFiles: "Синхронизированные файлы",
        myDevices: "Мои устройства",
        updateAvailable: "Доступна новая версия. Рекомендуется обновить.",
        updateButton: "Обновить",
        dismissButton: "Закрыть",
        folderDropPrompt: "Перетащите папку сюда или нажмите для выбора",
        folderDropDescription: "Рекурсивное сканирование подпапок · пакетное сжатие",
        folderDropOutput: "Выход: {root}/_velo_compressed/ (авто)",
        folderFilesUnit: "файлов",
        folderPickAnother: "Другая папка",
        folderScannedFiles: "Просканированные файлы",
        folderEmpty: "Сжимаемых файлов не найдено.",
        folderExcludeTooltip: "Исключить",
        readyToProcess: "Готово к обработке {count} файлов",
    },
    hi: {
        dropText: "वीडियो का आकार कम करने के लिए यहाँ खींचें",
        browse: "फ़ाइलें चुनें",
        files: "फ़ाइल कतार",
        queued: "प्रतीक्षारत",
        processing: "प्रसंस्करण...",
        completed: "पूर्ण",
        settings: "मूल सेटिंग्स",
        advanced: "उन्नत सेटिंग्स",
        format: "आउटपुट फ़ॉर्मेट",
        resolution: "रिज़ॉल्यूशन",
        audio: "ऑडियो",
        removeAudio: "ऑडियो हटाएं (म्यूट)",
        fileMgmt: "फ़ाइल प्रबंधन",
        moveToTrash: "संपीड़न के बाद मूल को ट्रैश में ले जाएं",
        start: "संपीड़न शुरू करें",
        stop: "रोकें",
        totalProgress: "कुल प्रगति",
        eta: "शेष समय",
        remove: "हटाएं",
        clearAll: "सब साफ़ करें",
        theme: "थीम",
        language: "भाषा",
        custom: "कस्टम",
        lockRatio: "अनुपात लॉक करें",
        quality: "संपीड़न गुणवत्ता",
        highQuality: "गुणवत्ता",
        highCompression: "संपीड़न",
        instagram: "Instagram (1080p)",
        youtube: "YouTube (4K)",
        originalSizeText: "मूल आकार",
        estResultText: "अनुमानित परिणाम",
        estReductionText: "औसत कमी",
        reductionOff: "OFF",
        batchNote: "SVT-AV1 इंजन {count} फ़ाइलों को अनुकूलित कर रहा है",
        outputDest: "सहेजने का स्थान",
        sameAsOriginal: "मूल के समान फ़ोल्डर",
        selectFolder: "गंतव्य फ़ोल्डर चुनें",
        saveTo: "इसमें सहेजें",
        legal: "शर्तें और गोपनीयता",
        activateTitle: "Velo सक्रिय करें",
        activateSub: "शक्तिशाली वीडियो संपीड़न को अनलॉक करने के लिए अपनी लाइसेंस कुंजी दर्ज करें।",
        licenseKey: "लाइसेंस कुंजी",
        activateBtn: "लाइसेंस सक्रिय करें",
        verifying: "लाइसेंस सत्यापित कर रहा है...",
        buyNow: "कुंजी नहीं है? अभी खरीदें",
        support: "सहायता",
        invalidKey: "अमान्य या समाप्त कुंजी।",
        machineLocked: "यह कुंजी पहले से किसी अन्य डिवाइस पर पंजीकृत है।",
        activationSuccess: "सक्रियण सफल! Velo में आपका स्वागत है।",
        turbo: "टर्बो मोड",
        turboTip: "हार्डवेयर त्वरण और अनुकूलित SVT-AV1 प्रीसेट के साथ 3 गुना तेज़ संपीड़न।",
        parallel: "समानांतर प्रसंस्करण",
        parallelTip: "एक साथ कई वीडियो संपीड़ित करें। उच्च मान अधिक CPU उपयोग करते हैं।",

        bestQuality: "सर्वोत्तम गुणवत्ता",
        bestQualityDesc: "मूल के समान दिखता है। ~30-50% कमी।",
        balanced: "संतुलित",
        balancedDesc: "साझा करने के लिए बढ़िया। अच्छी गुणवत्ता, अनुकूलित आकार।",
        smallestSize: "न्यूनतम आकार",
        smallestSizeDesc: "त्वरित संदेशों के लिए अधिकतम संपीड़न।",

        subjectiveVQ: "अनुभूति गुणवत्ता मैजिक",
        subjectiveVQTip: "मानव आँखों के लिए संवेदनशील क्षेत्रों (चेहरे, चमक) पर गुणवत्ता केंद्रित करता है। कम आकार, बेहतर दिखना।",
        hdr: "HDR रंग बनाए रखें (10-bit)",
        hdrTip: "iPhone/Galaxy HDR वीडियो के जीवंत रंगों को संरक्षित करता है।",
        metadata: "मेटाडेटा सफाई",
        metadataTip: "गोपनीयता की रक्षा के लिए तकनीकी मेटाडेटा (GPS, डिवाइस जानकारी) हटाता है।",

        highEfficiency: "अगली पीढ़ी का संपीड़न (AV1)",
        highEfficiencyTip: "AV1 तकनीक से ~30% बेहतर संपीड़न। प्लेबैक डिवाइस पर AV1 कोडेक चाहिए।",
        downloadCodec: "AV1 कोडेक डाउनलोड करें",
        folderOpen: "फ़ोल्डर में खोलें",
        taskType: "कार्य प्रकार",
        videoMode: "वीडियो संपीड़न",
        imageMode: "छवि संपीड़न",
        individualMode: "व्यक्तिगत",
        folderMode: "फ़ोल्डर",
        imageSettings: "छवि संपीड़न सेटिंग्स",
        signIn: "साइन इन",
        signOut: "साइन आउट",
        receivedFiles: "सिंक की गई फ़ाइलें",
        myDevices: "मेरे डिवाइस",
        updateAvailable: "नया संस्करण उपलब्ध है। अद्यतन की अनुशंसा।",
        updateButton: "अद्यतन",
        dismissButton: "बंद करें",
        folderDropPrompt: "फ़ोल्डर यहाँ खींचें या चुनने के लिए क्लिक करें",
        folderDropDescription: "सभी सबफ़ोल्डर का पुनरावर्ती स्कैन · बैच संपीड़न",
        folderDropOutput: "आउटपुट: {root}/_velo_compressed/ (स्वचालित)",
        folderFilesUnit: "फ़ाइलें",
        folderPickAnother: "दूसरा फ़ोल्डर",
        folderScannedFiles: "स्कैन की गई फ़ाइलें",
        folderEmpty: "कोई संपीड़न योग्य फ़ाइल नहीं मिली।",
        folderExcludeTooltip: "बहिष्कृत करें",
        readyToProcess: "{count} फ़ाइलों के प्रसंस्करण के लिए तैयार",
    },
};

// AV1 = MP4 컨테이너 + libsvtav1 코덱. 차세대 코덱 옵션 (HEVC 대비 ~30% 더 작음, 동일 화질).
export const FORMAT_OPTIONS = ['MP4', 'WebM', 'MKV', 'GIF', 'AV1'] as const;
export const RESOLUTION_OPTIONS = ['Original', '4K', '1080p', '720p', '480p', 'Instagram', 'YouTube', 'Custom'] as const;
